### ISSUE TITLE
bySum function doesn't work with more than one factor

### ISSUE THREAD

**Issue by schuemie** [edwindj/ffbase#40]
In [this line](https://github.com/edwindj/ffbase/blob/4941fc1fbb4bbb37d7aef9e002ca33d329169360/pkg/R/bySum.R#L20) the object `index` is referenced, but it doesn't exist if the `by` argument is a list. This causes an error when using `bySum()` with a list of factors.

**Comment by edwindj** [comment]
Thanks for reporting! I will look into it shortly

**Comment by edwindj** [comment]
Should be fixed: added an example that tests this feature. 
I suspect I accidentally removed a line (`index <- by`) so it stopped working...
