### ISSUE TITLE
importFrom("ff", "clone") in NAMESPACE?

### ISSUE THREAD

**Issue by vjcitn** [edwindj/ffbase#42]
I am finding that bit::clone can be called in ffappend.  The release version of
Bioconductor gQTLBase triggers this with example(storeToFf).  I find that it
is rectified when importFrom(ff, "clone") is added to ffbase NAMESPACE after "import(bit)".

**Comment by edwindj** [comment]
Thanks for reporting!

**Comment by edwindj** [comment]
I solved it differently (better I hope). Could you check with the latest github version if it is working for you? Thanks!

**Comment by vjcitn** [comment]
Yes, that solved it, thanks very much!
