### ISSUE TITLE
Error when subsetting ffdf which has rownames

### ISSUE THREAD

**Issue by nalimilan** [edwindj/ffbase#5]
I just got another error when subsetting a ffdf:

library(ffbase)
iris.ffdf <- as.ffdf(iris)

subset(iris.ffdf, Species="setosa") # OK

rownames(iris.ffdf) <- seq(nrow(iris))
subset(iris.ffdf, Species="setosa")
Error : is.null(rownames(x)) is not TRUE

traceback()
7: stop(sprintf(ngettext(length(r), "%s is not TRUE", "%s are not all TRUE"), 
       ch), call. = FALSE, domain = NA)
6: stopifnot(is.null(rownames(x)))
5: ffdfindexget(x, i)
4: `[.ffdf`(x, idx, select, drop = drop) at subset.R#37
3: x[idx, select, drop = drop] at subset.R#37
2: subset.ffdf(iris.ffdf, Species = "setosa")
1: subset(iris.ffdf, Species = "setosa")

Very weird error, but you will know better than I do. :-)

**Comment by schuemie** [comment]
I think this the same problem (but with different syntax):

```r
library(ffbase)

iris.ffdf <- as.ffdf(iris)

iris.ffdf[ffwhich(iris.ffdf, Species=="setosa"),]

rownames(iris.ffdf) <- seq(nrow(iris))

iris.ffdf[ffwhich(iris.ffdf, Species=="setosa"),]
#Error : is.null(rownames(x)) is not TRUE
```
