### ISSUE TITLE
Read.csv.ffdf not passing the quote parameter to scan()

### ISSUE THREAD

**Issue by ronald245** [edwindj/ffbase#55]
when attempting to read a Csv file that has every value in quotes (eg: "52.3605759") ffbase keeps throwing an error.

the function i'm using is:
 `read.csv.ffdf(file = reviews, quote = "\"")`

when i execute this line i get the following error message 
 `Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :  scan() expected 'a real', got '"51.5137335"'`

adding the decimal separator had no effect
`read.csv.ffdf(file = reviews, quote = "\"", dec = ".")`

i expect FF to pass the parameters to scan, and thus read the file.

EDIT: just realised this is an issue with the base FF, can be closed

**Comment by edwindj** [comment]
Thanks for reporting the issue! The function generating the error however is not part of `ffbase`but part of `ff` (which I am not the author of).  
You can contact that project at their website / maintainer: `http://r-forge.r-project.org/projects/ff/`
