### ISSUE TITLE
Unable to install ffbase

### ISSUE THREAD

**Issue by tianaowen** [edwindj/ffbase#59]
When I reinstalled the R package in r4.0，I found an ERROR.

> ** R
** byte-compile and prepare package for lazy loading
Error: object ‘is.factor.ff’ is not exported by 'namespace:ff'
Execution halted
ERROR: lazy loading failed for package ‘ffbase’
* removing ‘/home/tianaw/miniconda3/lib/R/library/ffbase’

The downloaded source packages are in
‘/tmp/RtmpT2wM3V/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("ffbase") :
  installation of package ‘ffbase’ had non-zero exit status

This seems to be because of a change in the 'ff' package, which was updated on July 30 (https://cran.r-project.org/web/packages/ff/index.html). The change seems to have broken the ffbase package, and the ffbase package has not been updated, including on github (https://github.com/edwindj/ffbase). 
Please give me some help, thank you very much.

**Comment by solis9753** [comment]
Any news on the above issue?

**Comment by solis9753** [comment]
@tianaowen is spot on regarding the changes in the ff package. ff no longer supports S3 classes, which relates to the error I am getting with is.factor.ff

https://github.com/truecluster/ff/issues/2#issuecomment-667018884

Plans to fix this?

**Comment by edwindj** [comment]
Thanks for reporting! I was on a holiday break: I will look into this shortly.

**Comment by edwindj** [comment]
Fixed it in the github repo, installing can be done with:

```
install_github("edwindj/ffbase", subdir="pkg")
```
Will upload version to CRAN asap

**Comment by edwindj** [comment]
CRAN is closed for new submissions until August 24 (holidays).

**Comment by edwindj** [comment]
The latest version is on CRAN, windows binaries should be available on August 26 2020
